version: '3'

services:
  master:
    image: redis
    container_name: rds-master
    command: rds-server --requirepass redis_pwd  --masterauth redis_pwd
    ports:
      - 6380:6379
  slave1:
    image: redis
    container_name: rds-slave-1
    ports:
      - 6381:6379
    command:  rds-server --slaveof rds-master 6379 --requirepass redis_pwd --masterauth redis_pwd
  slave2:
    image: redis
    container_name: rds-slave-2
    ports:
      - 6382:6379
    command: rds-server --slaveof rds-master 6379 --requirepass redis_pwd --masterauth redis_pwd
