version: '3'
networks:
  gin_template_es_network:

services:
  gin_template_elasticsearch:
    image: elasticsearch:7.11.2
    container_name: gin_template_elasticsearch
    environment:
      - node.name=gin_template_elasticsearch
      - cluster.name=es-cluster
      - discovery.seed_hosts=gin_template_elasticsearch,gin_template_elasticsearch2,gin_template_elasticsearch3
      - cluster.initial_master_nodes=gin_template_elasticsearch,gin_template_elasticsearch2,gin_template_elasticsearch3
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms150m -Xmx150m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ${PWD}/volumes/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - gin_template_es_network
  gin_template_elasticsearch2:
    image: elasticsearch:7.11.2
    container_name: gin_template_elasticsearch2
    environment:
      - node.name=gin_template_elasticsearch2
      - cluster.name=es-cluster
      - discovery.seed_hosts=gin_template_elasticsearch,gin_template_elasticsearch2,gin_template_elasticsearch3
      - cluster.initial_master_nodes=gin_template_elasticsearch,gin_template_elasticsearch2,gin_template_elasticsearch3
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms150m -Xmx150m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200
      - 9300
    volumes:
      - ${PWD}/volumes/elasticsearch2:/usr/share/elasticsearch/data # es集群每个节点的volume 映射位置不能相同
    networks:
      - gin_template_es_network
  gin_template_elasticsearch3:
    image: elasticsearch:7.11.2
    container_name: gin_template_elasticsearch3
    environment:
      - node.name=gin_template_elasticsearch3
      - cluster.name=es-cluster
      - discovery.seed_hosts=gin_template_elasticsearch,gin_template_elasticsearch2,gin_template_elasticsearch3
      - cluster.initial_master_nodes=gin_template_elasticsearch,gin_template_elasticsearch2,gin_template_elasticsearch3
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms150m -Xmx150m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200
      - 9300
    volumes:
      - ${PWD}/volumes/elasticsearch3:/usr/share/elasticsearch/data # es集群每个节点的volume 映射位置不能相同
    networks:
      - gin_template_es_network
  gin_template_kibana:
    container_name: gin_template_kibana
    image: kibana:7.11.2
    ports:
      - 5601:5601
    depends_on:
      - gin_template_elasticsearch
      - gin_template_elasticsearch2
      - gin_template_elasticsearch3
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - gin_template_es_network