version: '3'
networks:
  gin_template_kafka_network:

services:
  gin_template_zookeeper:
    image: wurstmeister/zookeeper
    container_name: gin_template_zookeeper
    ports:
      - 2181:2181
    networks:
      - gin_template_kafka_network
  gin_template_kafka:
    image: wurstmeister/kafka
    container_name: gin_template_kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP} # 这里写 自己本机的内网IP 或在 服务器公网IP
      KAFKA_ZOOKEEPER_CONNECT: gin_template_zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stream-in:1:1,stream-out:1:1"
    networks:
      - gin_template_kafka_network
    volumes:
      - ${PWD}/volumes/kafka/docker.sock:/var/run/docker.sock