version: '3'
networks:
  gin_template_network:

services:
  rabbitmq:
    hostname: rabbitmq_1
    container_name: rabbitmq_1
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    image: "rabbitmq:3.7.16-management"
    restart: always
    ports:
      - 15672:15672
      - 4369:4369
      - 5672:5672
      - 25672:25672
    volumes:
      - ${PWD}/volumes/rabbitmq:/var/lib/rabbitmq
    networks:
      - gin_template_network